# https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow

name: Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/devcontainers/ci/blob/main/docs/github-action.md
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/${{ github.repository }}
          # https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-and-check-in-a-project-specific-npmrc-file
          # when setting this in .npmrc in the repo we will be warned locally
          # cause we don't have the token, therefore we add the config remotely
          runCmd: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
            pnpm build
            pnpm -r publish --access public --no-git-checks
          env: |
            NPM_TOKEN=${{secrets.NPM_TOKEN}}
